language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.0.0

script:
  - dotnet restore ./src/Akka.Monitoring.Prometheus
  - dotnet build ./src/Akka.Monitoring.Prometheus
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then
  dotnet build ./src/Akka.Monitoring.Prometheus --configuration Release /p:Version=$TRAVIS_TAG;
  dotnet pack ./src/Akka.Monitoring.Prometheus --configuration Release /p:Version=$TRAVIS_TAG;
  nuget push ./src/Akka.Monitoring.Prometheus/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY;
  fi"